"use client";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { ArrowUpRight, Menu, X, Phone } from "lucide-react";

const nav=[{href:"/kylpyhuoneremontti",label:"Kylpyhuone"},{href:"/huoneistoremontti",label:"Huoneisto"},{href:"/keittioremontti",label:"Keittiö"},{href:"/referenssit",label:"Referenssit"},{href:"/nain-toimimme",label:"Näin toimimme"}];

export function SiteShell({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);return <><a className="skip-link" href="#main">Siirry sisältöön</a><header className="site-header"><div className="wrap header-inner"><Link className="brand" href="/" aria-label="Saneeraus Gurut, etusivu"><span className="brand-mark">SG<span>.</span></span><span className="brand-name">SANEERAUS<br/>GURUT</span></Link><nav className="desktop-nav" aria-label="Päävalikko">{nav.map(n=><Link href={n.href} key={n.href}>{n.label}</Link>)}</nav><div className="header-actions"><a className="header-phone" href="tel:+358503476660" aria-label="Soita numeroon 050 347 6660"><Phone size={17}/><span>050 347 6660</span></a><Link className="header-cta" href="/tarjouspyynto">Pyydä kartoitus</Link><button className="menu-button" type="button" aria-label={open?"Sulje valikko":"Avaa valikko"} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X size={26}/>:<Menu size={26}/>}</button></div></div>{open&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobiilivalikko">{nav.map(n=><Link onClick={()=>setOpen(false)} href={n.href} key={n.href}>{n.label}<ArrowUpRight size={17}/></Link>)}<Link onClick={()=>setOpen(false)} href="/yritys">Yritys<ArrowUpRight size={17}/></Link><Link onClick={()=>setOpen(false)} href="/yhteystiedot">Yhteystiedot<ArrowUpRight size={17}/></Link></nav>}</header><main id="main">{children}</main><footer className="footer"><div className="wrap footer-grid"><div><Link href="/" className="footer-logo">SG<span>.</span></Link><p>Saneeraus Gurut Oy<br/>Remontit Keski-Uudellamaalla.</p></div><div><h2>Palvelut</h2><Link href="/kylpyhuoneremontti">Kylpyhuoneremontit</Link><Link href="/huoneistoremontti">Huoneistoremontit</Link><Link href="/keittioremontti">Keittiöremontit</Link></div><div><h2>Tutustu</h2><Link href="/referenssit">Referenssit</Link><Link href="/nain-toimimme">Näin toimimme</Link><Link href="/yritys">Yritys</Link><Link href="/tarjouspyynto">Tarjouspyyntö</Link></div><div><h2>Ota yhteyttä</h2><a href="tel:+358503476660">050 347 6660</a><a href="mailto:kari@saneerausgurut.fi">kari@saneerausgurut.fi</a><span>Forssankatu 4, 04430 Järvenpää</span></div></div><div className="wrap footer-bottom"><span>© 2026 Saneeraus Gurut Oy</span><Link href="/tietosuoja">Tietosuoja</Link></div></footer><div className="mobile-sticky"><a href="tel:+358503476660"><Phone size={18}/> Soita</a><Link href="/tarjouspyynto">Pyydä kartoitus</Link></div></>}

export function Cta({href,children}:{href:string,children:React.ReactNode}){return <Link className="button-primary" href={href}>{children}<ArrowUpRight size={19}/></Link>}
export function SectionIntro({kicker,title,description}:{kicker:string,title:string,description?:string}){return <div className="section-intro"><span className="kicker">{kicker}</span><div><h2>{title}</h2>{description&&<p>{description}</p>}</div></div>}
export function ServiceCard({number,title,description,href}:{number:string,title:string,description:string,href:string}){return <Link className="service-card" href={href}><span className="service-number">{number} / PALVELU</span><div className="service-icon"><span className="mini-grid"><i/><i/><i/><i/></span></div><h3>{title}</h3><p>{description}</p><span className="service-bottom">Tutustu palveluun <ArrowUpRight size={20}/></span></Link>}
export function PhotoPanel({className="",label}:{className?:string,label:string}){return <div className={"photo-panel "+className}><Image fill priority sizes="(max-width: 800px) 100vw, 48vw" src="https://le-de.cdn-website.com/448e4c656a21430e8cc5daa0898b5b95/dms3rep/multi/opt/WhatsApp%2BImage%2B2026-09-17%2Bat%2B09.42.40-1095w.jpeg" alt="Saneeraus Gurujen nykyisellä sivustolla julkaistu keittiökuva"/><div className="photo-label"><span className="photo-cross">＋</span>{label}</div></div>}
export function Faq({items}:{items:[string,string][]}){return <div className="faq-list">{items.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">＋</span></summary><p>{a}</p></details>)}</div>}
