import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { ArrowUpRight, Check } from "lucide-react";
import { Cta, Faq, SiteShell } from "../site-components";
import { FinalCall } from "../page";

type Service = {title:string;intro:string;number:string;things:string[];situations:string[];faq:[string,string][]};
const services:Record<string,Service>={
 "kylpyhuoneremontti":{number:"01",title:"Kylpyhuoneremontti",intro:"Kun kylpyhuone kaipaa uudistusta, työn sisältö kannattaa määritellä huolellisesti. Saneeraus Gurut toteuttaa kylpyhuoneremontteja Järvenpään, Keravan ja Tuusulan seudulla.",things:["Vanhan tilan purku ja pohjatyöt","Vedeneristys ja laatoitus","Kalusteiden asennus","Tarvittavien sähkö- ja LVI-töiden yhteensovittaminen"],situations:["Tila on vanhentunut tai toimimaton","Pinnat ja kalusteet halutaan uusia","Kylpyhuone on osa laajempaa remonttia"],faq:[["Miten hinta määritellään?","Työn laajuus, rakenteiden lähtötilanne ja materiaalit vaikuttavat hintaan. Lopullinen sisältö ja tarjous määritellään kohteen kartoituksen perusteella."],["Kuinka kauan remontti kestää?","Kesto riippuu tilasta ja työvaiheista. Kohteelle sovitaan aikataulu työn sisällön selvittyä."],["Voinko lähettää kuvia etukäteen?","Kyllä. Lisää kuvia tarjouspyynnön mukana, niin lähtötilannetta on helpompi arvioida."]]},
 "huoneistoremontti":{number:"02",title:"Huoneistoremontti",intro:"Yksittäisten pintojen päivitys tai laajempi kodin uudistus. Selvitetään yhdessä, mitä tiloissa kannattaa tehdä ja miten eri työvaiheet liittyvät toisiinsa.",things:["Seinien ja kattojen pintatyöt","Lattiat ja listoitukset","Tilojen ja kalusteiden uudistus","Kokonaisuuteen kuuluvien töiden yhteensovittaminen"],situations:["Koti kaipaa uutta ilmettä","Useita tiloja halutaan remontoida samalla kertaa","Pohjaratkaisua tai arjen toimivuutta halutaan parantaa"],faq:[["Voiko remontoida vain osan huoneistosta?","Kyllä, työn laajuus voidaan rajata yhteen tai useampaan tilaan."],["Mistä hinta muodostuu?","Hinta perustuu sovittuihin työvaiheisiin, kohteen lähtötilanteeseen ja materiaaleihin."],["Miten eri työvaiheet sovitetaan yhteen?","Työn sisältö ja toteutusjärjestys käydään läpi ennen aloitusta."]]},
 "keittioremontti":{number:"03",title:"Keittiöremontti",intro:"Keittiö voidaan päivittää osittain tai uudistaa kokonaan. Hyvä lähtökohta on selvittää, mikä nykyisessä tilassa toimii ja mitä haluat muuttaa.",things:["Kalusteiden ja tasojen uusiminen","Välitilan ja pintojen päivitys","Lattian ja valaistuksen muutokset","Tarvittavien sähkö- ja LVI-töiden yhteensovittaminen"],situations:["Keittiö ei palvele nykyistä arkea","Kalusteet tai pinnat ovat kuluneet","Tila uusitaan osana muuta remonttia"],faq:[["Riittääkö ovien ja tasojen uusiminen?","Se riippuu nykyisten runkojen kunnosta ja toivotusta muutoksesta. Kartoituksessa voidaan verrata vaihtoehtoja."],["Miten keittiöremontin hinta määräytyy?","Hinta riippuu uusittavista osista, materiaaleista ja tarvittavista asennustöistä."],["Voinko lähettää kuvia nykyisestä keittiöstä?","Kyllä. Liitä kuvat tarjouspyyntöön ja kerro, mitä haluaisit muuttaa."]]}
};

export function generateStaticParams(){return [...Object.keys(services),"referenssit","nain-toimimme","yritys","yhteystiedot","tietosuoja"].map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services[slug];const names:Record<string,string>={referenssit:"Referenssit", "nain-toimimme":"Näin toimimme",yritys:"Yritys",yhteystiedot:"Yhteystiedot",tietosuoja:"Tietosuoja"};return {title:s?s.title+" Järvenpää, Kerava ja Tuusula":names[slug]||"Sivu",description:s?s.intro:undefined}}
export default async function ContentPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services[slug];if(s)return <SiteShell><div className="wrap page-hero"><div><span className="kicker">{s.number} / PALVELU</span><h1>{s.title} Keski-Uudellamaalla.</h1><p>{s.intro}</p><div className="actions"><Cta href={"/tarjouspyynto?palvelu="+encodeURIComponent(s.title)}>Pyydä kartoitus</Cta><Link className="text-link" href="/referenssit">Referenssit <ArrowUpRight size={18}/></Link></div></div><div className="page-hero-side"><span>JÄRVENPÄÄ / KERAVA / TUUSULA</span><strong>Remontin hyvä alku on selkeä keskustelu.</strong></div></div><section className="wrap content-section"><span className="kicker">MILLOIN REMONTTI ON AJANKOHTAINEN?</span><h2>Lähtötilanne ratkaisee toteutuksen.</h2><div className="info-grid">{s.situations.map((x,i)=><div key={x}><span>0{i+1} / TILANNE</span><h3>{x}</h3><p>Kerro tilanteestasi, niin työn sisältö voidaan rajata oikein.</p></div>)}</div></section><section className="wrap content-section"><span className="kicker">TYÖN SISÄLTÖ</span><h2>Mitä {s.title.toLowerCase()} voi sisältää?</h2><p className="intro">Tarkka työmäärä sovitaan aina kohteen perusteella. Tässä tavallisia kokonaisuuteen kuuluvia työvaiheita.</p><ul className="check-list">{s.things.map(t=><li key={t}><Check size={19}/>{t}</li>)}</ul></section><section className="wrap content-section"><div className="empty-proof"><span>TOTEUTETTU KOHDE / KUVA-AINEISTO</span><strong>Vahvistetut kohdekuvat ja työn tiedot lisätään tähän.</strong></div><p className="aside-note">Emme esitä kuvituskuvaa asiakkaan referenssinä. <Link href="/referenssit">Katso referenssien tila <ArrowUpRight size={15}/></Link></p></section><section className="wrap content-section"><span className="kicker">ETENEMINEN</span><h2>Ensin kohde, sitten tarjous.</h2><div className="info-grid"><div><span>01</span><h3>Kerro tarpeesta</h3><p>Lähetä lyhyt kuvaus kohteesta ja halutessasi kuvia.</p></div><div><span>02</span><h3>Selvitetään työ</h3><p>Käydään läpi lähtötilanne ja sopiva toteutuksen laajuus.</p></div><div><span>03</span><h3>Sovitaan ehdot</h3><p>Työn sisältö, hinta ja aikataulu määritellään tarjouksessa.</p></div></div></section><section className="wrap content-section narrow"><span className="kicker">USEIN KYSYTTYÄ</span><h2>Kysymyksiä {s.title.toLowerCase()}sta</h2><Faq items={s.faq}/></section><FinalCall/></SiteShell>;
const content:Record<string,React.ReactNode>={
 "referenssit":<><PageHero kicker="TYÖN JÄLKI" title="Toteutettuja remontteja" description="Oikeat kohdekuvat, työvaiheet ja asiakkaan lupa tarvitaan ennen referenssin julkaisua."/><section className="wrap content-section"><div className="empty-proof"><span>REFERENSSIT / ODOTTAA AINEISTOA</span><strong>Tähän tulevat kuvat ja tiedot vahvistetuista toteutuksista.</strong></div><p className="plain-body">Haluatko nähdä yrityksen toteutuksia ennen yhteydenottoa? Kysy sopivista kohteista suoraan yhteyshenkilöltä.</p><Cta href="/yhteystiedot">Ota yhteyttä</Cta></section></>,
 "nain-toimimme":<><PageHero kicker="TOIMINTATAPA" title="Näin remontti etenee" description="Selkeä eteneminen auttaa tekemään päätöksen oikeilla tiedoilla. Lopulliset käytännöt vahvistetaan kunkin projektin yhteydessä."/><section className="wrap content-section"><div className="info-grid">{[["01","Yhteydenotto","Kerro lyhyesti kohteesta ja toivotusta muutoksesta."],["02","Kartoitus","Lähtötilanne ja työn laajuus käydään läpi."],["03","Tarjous","Sovitusta työstä annetaan tarjous."],["04","Aikataulu","Aloitus ja työn eteneminen sovitaan."],["05","Toteutus","Työ tehdään sovitun sisällön mukaisesti."],["06","Luovutus","Valmis työ käydään läpi."]].map(([n,t,d])=><div key={n}><span>{n} / VAIHE</span><h3>{t}</h3><p>{d}</p></div>)}</div></section></>,
 "yritys":<><PageHero kicker="SANEERAUS GURUT OY" title="Paikallinen remonttikumppani." description="Saneeraus Gurut Oy tarjoaa kylpyhuone-, huoneisto- ja keittiöremontteja Järvenpään, Keravan ja Tuusulan alueella."/><section className="wrap content-section narrow"><h2>Otetaan projekti puheeksi.</h2><p className="plain-body">Yrityksen yhteyshenkilö Kari Kuru kertoo lisää toimintatavasta ja arvioi kanssasi, sopiiko suunnittelemasi työ yritykselle. Henkilöesittely, pätevyydet ja dokumentoidut referenssit lisätään, kun tiedot on vahvistettu.</p><Cta href="/yhteystiedot">Yhteystiedot</Cta></section></>,
 "yhteystiedot":<><PageHero kicker="OTA YHTEYTTÄ" title="Kerro remontistasi." description="Voit soittaa, lähettää sähköpostia tai kuvata projektisi tarjouspyyntölomakkeella."/><section className="wrap content-section"><div className="contact-grid"><div className="contact-card"><span>PUHELIN</span><a href="tel:+358503476660">050 347 6660</a><p>Soita ja kerro kohteestasi.</p></div><div className="contact-card"><span>SÄHKÖPOSTI</span><a href="mailto:kari@saneerausgurut.fi">kari@saneerausgurut.fi</a><p>Kari Kuru / Saneeraus Gurut Oy</p></div></div><p className="plain-body">Forssankatu 4, 04430 Järvenpää</p><Cta href="/tarjouspyynto">Täytä tarjouspyyntö</Cta></section></>,
 "tietosuoja":<><PageHero kicker="TIETOSUOJA" title="Tietoa yhteydenotosta." description="Sivuston tarjouspyyntölomake kerää vain pyynnön käsittelyyn tarvittavat tiedot."/><section className="wrap content-section narrow plain-body"><h2>Tarjouspyynnön tiedot</h2><p>Rekisterinpitäjä on Saneeraus Gurut Oy. Lomakkeella annettu nimi, yhteystiedot, remontin kuvaus, sijainti ja mahdolliset kuvat välitetään yrityksen sähköpostiin Resend-palvelun kautta yhteydenoton käsittelyä varten. Tietoja ei julkaista sivustolla.</p><p>Pyydä lisätietoa tietojen käsittelystä tai tietojesi poistamista osoitteesta <a href="mailto:kari@saneerausgurut.fi"><u>kari@saneerausgurut.fi</u></a>. Säilytysajat ja mahdolliset palveluntarjoajaa koskevat tiedot tulee vahvistaa ennen sivuston julkista käyttöönottoa.</p></section></>
};if(!content[slug])notFound();return <SiteShell>{content[slug]}<FinalCall/></SiteShell>}
function PageHero({kicker,title,description}:{kicker:string,title:string,description:string}){return <section className="wrap page-hero"><div><span className="kicker">{kicker}</span><h1>{title}</h1><p>{description}</p></div><div className="page-hero-side"><span>SANEERAUS GURUT / KESKI-UUSIMAA</span><strong>Käytännöllinen päätös alkaa oikeista tiedoista.</strong></div></section>}
