"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpRight } from "lucide-react";
import Link from "next/link";
const choices=["Kylpyhuone","Huoneisto","Keittiö","Vesivahinko","Terassi / ulkotila","Muu"];
export default function RequestForm({initialService=""}:{initialService?:string}){const router=useRouter();const initial=initialService.replace("remontti","");const [service,setService]=useState(choices.includes(initial)?initial:""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!service){setError("Valitse remontin tyyppi.");document.getElementById("service-title")?.focus();return}setBusy(true);const form=new FormData(e.currentTarget);form.set("service",service);try{const response=await fetch("/api/tarjouspyynto",{method:"POST",body:form}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"Lähetys epäonnistui.");router.push("/kiitos")}catch(err){setError(err instanceof Error?err.message:"Lähetys epäonnistui.");setBusy(false)}}
return <form className="request-form" onSubmit={send} encType="multipart/form-data"><div className="form-step"><h2 id="service-title" tabIndex={-1}><span>01 /</span> Mitä olet remontoimassa?</h2><div className="choice-grid" role="radiogroup" aria-labelledby="service-title" aria-required="true">{choices.map(c=><label key={c}><input type="radio" name="service_choice" value={c} checked={service===c} onChange={()=>setService(c)}/><span>{c}</span></label>)}</div></div><div className="form-step"><h2><span>02 /</span> Missä kohde sijaitsee?</h2><div className="field-row"><label className="field">Paikkakunta *<input name="city" required maxLength={100} autoComplete="address-level2" placeholder="Esim. Järvenpää"/></label><label className="field">Postinumero<input name="postcode" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} autoComplete="postal-code" placeholder="Esim. 04430"/></label></div></div><div className="form-step"><h2><span>03 /</span> Kerro projektista</h2><label className="field">Mitä haluaisit tehdä? *<textarea name="description" required maxLength={3000} placeholder="Kuvaile nykytilanne ja toivottu muutos..." /></label></div><div className="form-step"><h2><span>04 /</span> Lisää kuvia <small>(vapaaehtoinen)</small></h2><label className="upload-box">Kuvia nykyisestä tilasta<input name="images" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{if((e.currentTarget.files?.length||0)>5){e.currentTarget.value="";setError("Voit liittää enintään 5 kuvaa.")}else setError("")}}/><small>Enintään 5 kuvaa, JPG/PNG/WebP, korkeintaan 3 Mt per kuva.</small></label></div><div className="form-step"><h2><span>05 /</span> Yhteystiedot</h2><div className="field-row"><label className="field">Nimi *<input name="name" required maxLength={150} autoComplete="name"/></label><label className="field">Puhelin *<input name="phone" type="tel" required maxLength={50} autoComplete="tel"/></label></div><label className="field">Sähköposti *<input name="email" type="email" required maxLength={200} autoComplete="email"/></label><label className="field" style={{position:"absolute",left:"-9999px"}} aria-hidden="true">Verkkosivu<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="aside-note">Tietojasi käytetään yhteydenoton käsittelyyn. <Link href="/tietosuoja">Tietosuoja</Link></p></div>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button-primary form-submit" type="submit" disabled={busy}>{busy?"Lähetetään...":"Lähetä remonttipyyntö"}<ArrowUpRight size={19}/></button></form>}
